syncthing:
    key: ENC[AES256_GCM,data:0axnPDiBRo7L6JKP+LyP10ruXb93ij8a1P/tn29OfY542iBq/OQr8X98KqmmaYo78Km8NdVyzbBkAOnqjNlgWzVwR1plBICLFZoyGFAFjD7skjHP99Yw3Gi+O9sxFV60zfQ5qpkcvl35gbgg44JN3EYnmCmaoIU=,iv:Clt69oIiHJRImyTl0HsCtSeYsMbtinGcz89jDy3dvQM=,tag:lNxAaZeUDdWTp391iXHbJw==,type:str]
    cert: ENC[AES256_GCM,data:UqmNTfF6ALGAbPoqfwiojbA+urNfBKPKLY7+gbju6fxEpgRtJmrs6cDZ/6fNELt9DaVqJXLeEX9PLktIMQgy2HRv4Fb64yE1yLSu1jm1qag87jY49lHIvq+/TBSruekocKSluPo+V5tDSwCTDtKpuX30nXikfsEzwPhj85dE5L0TK2tvBqh2lcOS9cQ61slexq/ZKUD0Cvu9UmAWvJ6Ju875GGOrK+AuKiE9+dyriSdONeB1eLTEuwBoinrUI4PqH0fdoN1gmIHIGzYXfX+ct7nrzqEZKrCt1Y75FN9R4oL13MfV6XwGYsQlUoQgRB2SZDfHd7A8hl+nT5NvwPf/vDVFuehfR8AW6qRS7xagu9qeTwfFilijWqp7mb2T7Y8+YIZN1ihBJ3Cy4K29Qk7ME1qYOMlRBTzHzfzgvPuSZWBnZWqyfGzoUGW4NXT2hdtW6Vqa/NZgEXm62anqMwJhXa1ZuRKOE5WBD5W7TD3uwZRDWUYV210dW26IuXmi9ljfTv5MxANP8+3/fr5Id43low35IqOsxfpRiAVQ2uZ6uTF2yMy3VEPlJwiNw36qLuO3MrqN4ml+z5zz4fm6I51anqFhFnBZjUPV61X235oJ9g/2xr8Dt+9WKvPkHlUJIGU0GpL5fOwt2jsMqBojbocJX1niBBlDlQSW/Uzv0KVI/bR//sBM+PotqLGx/wqpfSPtpJPXfldnCX3i71zzHLZOiYKKAVpuRwy+Yq1tAckf+7l+PeeDdJaoQKWDsuOvz9suiQDZJzzqglCgra2LXdCs5OZrB5oVlESehmeDcnsr+x/S4yw4Mb9aMuAx7FkflGY=,iv:4tfGBztjV++c6QfRMQUox4Bz+c/b4F9kHA5eIWRoDvA=,tag:cnEzaePQVNE1qxdObOgtvA==,type:str]
apiKeys:
    tavily: ENC[AES256_GCM,data:PYE0o7N9++retUuUpQb73Xifxu9Tj6/5eO6VHJjUar7EAwcy+715rFg=,iv:LdXYwrVnxCmzm7nv1FZD4F0DGd2g7jJCZOhwzOZenVw=,tag:8Nm8uQTtGV28lR7Ix85BGw==,type:str]
    huggingface: ENC[AES256_GCM,data:CULkP/6oT0ZPMwWGZWMg78/1iTbZVFEsbpxwUJE3VbGDyhYQvg==,iv:TQkjeHpwb7S4OSDwe3oDWPEQmn02d8xtkfbJ5lPRMCw=,tag:fTyrPY1u0V9UQqRY7PEvOw==,type:str]
ssh:
    identity:
        private: ENC[AES256_GCM,data:KNAzMkS7pLnniLkqVLpTZvkDJdsyh8QXED+szcH1bDAvjzsFSykvjhVGssC1ogahk1VP+PWHyocDN1J2cf77lqz/xzORWGExRHW13tpwq8bexTvH/jG8Fcoh+7XDROX/xoSehRqoHwoNmZhSvF0/hqKasuGLWWBjZg2TMpkqNTUg24VxuSUzrWTCnGPNqe/aSH3Dx/xMN9Ewnpb6PLElpA6Fg5N7Q4xYJfEgy/XQkHnp3YcIYDml/Iyo01sEVdmwDEJYbItR6uW5ElJ7VPd9Kr1Ym192gcc3+BgWiRFAldSEJLPAPRRyzC6XnoBUIHjnXeemopce9odyE/zqnlNVwtJI6FU/BWIObT/LoOu+x3NmN5JHiho05u7ERgZa9ZxQRy+zaTWSr5sgNc1CNYPhZoj3Z9PzGwyzKHXyIfuzxCcCupdONIEJRhkEnpC5B6MT/ItfZEg5jWenf7t8X084b1yzaFplIam6yhKtKsXMUKLRzUFODIqQOe5CdDe79zz1uYA9E8KOa3Ma/imyX4Lv4XJUWorh4TT0eG0y0Ca29KjKMSi+m8KRwIKDuFrdQEdIS297xdCKw+qRxsz8Ups/OSaFpIhr+T2pHdyF3L/ZzOY=,iv:RbF4Uzfkj75cmD3EIVKfRCIqc79F9r+RvhQUPfxry+0=,tag:vLVs7MfZ8voGBTJ+/ziPGQ==,type:str]
        public: ENC[AES256_GCM,data:DJnTLD65Hd+SwkkW6+Lgfcq50fUHYVRXjgH6V0gQlK3z48wRVyvD+pdOsQJaroh535jV3o36nY7nYcTwpf0+ToAS4gN/6Pc4LYu8Lro9GGJ0BlMkARxYNYVBknSaQtNPfEI=,iv:TlLMmJVvfaNxCYp44fejJLo7IJY5rLp+kbbvH2jdB7o=,tag:FRBAq96baw9peHRD34WETw==,type:str]
sops:
    age:
        - recipient: age1xvyp63kuszp4u0ke4lf84wstgt6td04v6w605twh3mwqaedv9u8sdm8g4j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsbjV3MzBYZmg1dnQwM25R
            Zk02WnRLT2lBV1ZSRVlmK3lmWWl1WTdvRmw0Cis4bm5Oc3NDMXF3Y0tydGphWDNH
            dzVlUXMxL2ovVkpRaTJsdHlhaXZVU2sKLS0tIFlyUWZKZlJJejZKVUxSc1BxQ2w0
            dVZqeHpoSW5Fb0wvdnlNQWdQZWV4L0kKLZ5N6L/7rwy4WeNGuJQK66vBtS/jJ1qz
            x6to8xi3oKAD4q9efCxFiCAvWCgbESFjsqNAztN+vJMnFqBh/a05vg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vqn62ymk3g06u789u9ku609face4lnmlf4gsnw7lxjdet3wsv5yq68cnrf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDY2FHK0dFWERKYVRqRWRx
            RVRnSGVCS0ZMb3NlWVR5NGdaNE8xeWVoQzFZClBqWkVaWWRReUJ3cWRCc2c3b2JM
            ZWNCVS8rODVFYWJydXUzdE56QWV0VGcKLS0tIDQ1S0JkR3ZWa1VsWjdTUThtdWs3
            L0I5aU5YK2pBeElnVllxVzlNTldpV0kKuqQ3Q32smgQ4BllSX0LcppvWsEWMp3xT
            V/fhx7mGxqXD/GgWh7knaMW2wdcgY/tgQrbmpHbUf9eqKSlTo8LjMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-10T03:16:11Z"
    mac: ENC[AES256_GCM,data:DHbQjdIz91tgR5aeOH91uPH0Hg3Gt3VyD1i/YwfAC3JCUPSoOu4R916yU4EHBv8EKvFELCdumf/C3jWTkWucZsDH64vJCVC80V0tnaQo+gRQgb+5Tw3S61qp7jeRoMi7BsYQd4d7S3XygpXy1FqKSxILPXJDUgQqA6W84nDgiuU=,iv:JEqYFTl4T2Xp7vDkqdN/H7yb5yL1YSxFi0q9hR/iWyk=,tag:e5vAMgeOoVtgUEAbprKiaA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
